### ISSUE TITLE
Why vander_generic is slower for Float32 than Float64

### ISSUE THREAD

**Issue by michaellass** [crstnbr/JuliaNRW21#4]
There was the question on day 1 why `vander_generic` is slower for Float32 than for Float64 and and using the Float64 variant even for Float32 seems to be beneficial:
https://github.com/crstnbr/JuliaNRW21/blob/337eacb40950ea37c5e0de485fe7ecb9192efb68/Day1/5_generic_programming.ipynb#L197

Comparing the assembly shows that calls to an out-of-bounds check (`jl_bounds_error_ints`) appear more often in the Float32 version than the Float64 version. This seems to be the reason for the slowdown. Telling Julia that all indices are within range of the vectors/matrices significantly speeds up the routine:

Data:
```julia
x = rand(Float64, 100)
y = rand(Float32, 100)
```

Original:
```julia
@btime vander_generic($x)
  6.579 μs (2 allocations: 78.20 KiB)
@btime vander_generic($y)
  8.125 μs (2 allocations: 39.14 KiB)
```

Modified:
```julia
@btime vander_generic($x)
  4.098 μs (2 allocations: 78.20 KiB)
@btime vander_generic($y)
  2.615 μs (2 allocations: 39.14 KiB)
```

Modified code:
```julia
function vander_generic(x::AbstractVector{T}) where T
    m = length(x)
    V = Matrix{T}(undef, m, m)
    for j = 1:m
        @inbounds V[j,1] = one(T)
    end
    for i= 2:m
        for j = 1:m
            @inbounds V[j,i] = x[j] * V[j,i-1]
        end
    end
    return V
end
```

Maybe something for the Performance Gotchas session tomorrow?

**Comment by carstenbauer** [comment]
Good catch. However, it's still not clear why the `Float32` version without `@inbounds` is slower, i.e. why there are more out-of-bounds checks in this case than for `Float64`. Or am I missing something?

**Comment by carstenbauer** [comment]
Actually, on my machine the `@inbounds` doesn't solve the issue:

```Julia
julia> function vander_generic(x::AbstractVector{T}) where T
           m = length(x)
           V = Matrix{T}(undef, m, m)
           for j = 1:m
               @inbounds V[j,1] = one(T)
           end
           for i= 2:m
               for j = 1:m
                   @inbounds V[j,i] = x[j] * V[j,i-1]
               end
           end
           return V
       end
vander_generic (generic function with 1 method)

julia> x = rand(Float64, 100);

julia> y = rand(Float32, 100);

julia> @btime vander_generic($x);
  4.513 μs (2 allocations: 78.20 KiB)

julia> @btime vander_generic($y);
  13.734 μs (2 allocations: 39.14 KiB)
```

**Comment by michaellass** [comment]
> However, it's still not clear why the `Float32` version without `@inbounds` is slower, i.e. why there are more out-of-bounds checks in this case than for `Float64`. Or am I missing something?

That part is also unclear to me. I did not really try to understand the assembly, I just noticed that there is an additional block in there calling that function.

> Actually, on my machine the `@inbounds` doesn't solve the issue:

That's interesting. So still some mysteries left...

**Comment by carstenbauer** [comment]
A guess is that this is a cache alignment effect. That could also explain why it is machine dependent and why `@inbounds` which facilitates SIMD can lift the issue in some cases. But this is above my pay grade :)

**Comment by carstenbauer** [comment]
```Julia
julia> function f(x::AbstractVector{T}) where T
                  m = length(x)
                  V = Matrix{T}(undef, m, m)
                  for j = 1:m
                      @inbounds V[j,1] = one(T)
                  end
                  for i= 2:m
                      for j = 1:m
                         @inbounds V[j,i] = x[j] * V[j,i-1]
                      end
                  end
                  return V
              end
f (generic function with 1 method)

julia> set_zero_subnormals(false) #default
true

julia> @btime f($x);
  4.636 μs (2 allocations: 78.20 KiB)

julia> @btime f($y);
  16.035 μs (2 allocations: 39.14 KiB)

julia> set_zero_subnormals(true)
true

julia> @btime f($x);
  5.247 μs (2 allocations: 78.20 KiB)

julia> @btime f($y);
  2.589 μs (2 allocations: 39.14 KiB)
```

But don't ask me what `set_zero_subnormals` does exactly :)

**Comment by carstenbauer** [comment]
A comment by @chriselrod on the Julia Slack regarding alignment:

> With 100x100 and 256-bit vectors, Float64 would be perfectly aligned, while only every other column of V will be aligned with Float32, so if you did SIMD the cartesian loops, you'd be at one of the peaks for Float64 but not for Float32 in that matrix_vector_ops link.

**Comment by michaellass** [comment]
I also found a machine where I could reproduce your results. I already tried increasing the size to multiples of 256 bits but that did not make a difference. Also Julia and LLVM versions and the operating systems don't seem make a difference. But you found the reason in the subnormals! They will occur much more frequently with Float32 than with Float64. And I can reproduce your results when setting `set_zero_subnormals(true)`. That way, subnormals will just be set to 0. Looks like the performance impact is very hardware dependent.

Also see https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/floating-point-operations/understanding-floating-point-operations/denormal-numbers.html

Fascinating! Thanks for sticking with me here :slightly_smiling_face:

**Comment by chriselrod** [comment]
> But don't ask me what `set_zero_subnormals` does exactly :)

Operating on subnormal numbers are very slow (but just how much slower is architecture dependent).
Your 
Your CPU can either be slow, or has an option to instead treat them as `0`.

Subnormal number's exponent bits are all 0:
```julia
julia> bitstring(1e-308)[1:12]
"000000000000"

julia> bitstring(1e-307)[1:12]
"000000000011"
```
Note that they're actually set to `0`, just treated as `0`:
```julia
julia> 1e-308
0.0

julia> bitstring(ans)
"0000000000000111001100001101011001111000000110011110100011010010"
```
Most CPUs have flags that determine how they handle subnormal numbers.
The default in Julia is to be correct but slow.
`set_zero_subnormal`s lets the CPU instead treat them as 0/flush them to 0 which doesn't suffer any penalty.

Maximum subnormal and minimum non-subnormals are:
```julia
julia> x = abs(reinterpret(Float64, typemax(UInt) & (~Base.exponent_mask(Float64))))
2.225073858507201e-308

julia> y = nextfloat(x)
2.2250738585072014e-308

julia> issubnormal.((x,y))
(true, false)
```

**Comment by carstenbauer** [comment]
Great that we could find an answer! Let's close this.
