### ISSUE TITLE
Possible solutions for day 2/3b_exercise_optimization2

### ISSUE THREAD

**Issue by fbanning** [crstnbr/JuliaNRW21#5]
As you specifically asked for possible solutions to see how we approached the exercises, here's my approach:

Benchmark for the provided base version of `work!` was ~21 MIt/s.

1. Respect column major order. This is a simple matter of switching `i` and `j` in the indexing calls to `A` and `B`. Of course it could also be done via switching `i` and `j` in the line starting the for-loop instead.
2. Reduce separate calculation of duplicate sin and cos (and thus allocations) by computing them once and squaring the result. This could be simplified even further as you did it.

Also I've attempted reduce visual clutter by combining the two nested for loops. note that this directly couples the loops so it's not always a good idea to do it like this. just to be sure this isn't misunderstood: there's no performance gain in this but simply reduces the amount of needed indentations.

```julia
function work1!(A, B, v, N)
    val = 0
    for i=1:N, j=1:N
        val = mod(v[i],256);
        A[j,i] = B[j,i]*(sin(val)^2 - cos(val)^2);
    end
end
```

Performance was increased to ~50 MIt/s.

3. Preallocate empty `vals` array either with or without given length `N`, calculate `val` and push them into the `vals` array. two ways to do this:

```julia
function work2!(A, B, v, N)
    vals = zeros(Float64, N)
    
    for i=1:N
        val = mod(v[i],256)
        vals[i] = sin(val)^2 - cos(val)^2
    end
    
    for i=1:N, j=1:N
        A[j,i] = B[j,i] * vals[i];
    end
end

function work3!(A, B, v, N)
    vals = Float64[]
    
    for i=1:N
        val = mod(v[i],256)
        push!(vals, (sin(val)^2 - cos(val)^2))
    end
    
    for i=1:N, j=1:N
        A[j,i] = B[j,i] * vals[i];
    end
end
```

Performance for both `work2!` and `work3!` increases to ~760 MIt/s.
For these two it comes down to stylistic choice as it seems. I personally prefer `work3!` as I find it nicer to read and it doesn't require prior knowledge of the vector length but that's not so important.

**Comment by carstenbauer** [comment]
Thanks for your post! I will somehow archive the solutions and also use the attempts to optimise the exercise.
